### ISSUE TITLE
Client crashes with multiple Header Values

### ISSUE THREAD

**Issue by SirWellington** [SirWellington/alchemy-http#6]
The HTTP Client crashes when it receives multiple header values for one header name,
for example

GitHub APIs often return

```
Vary: Accept, Authorization, Cookie, X-GitHub-OTP
```

This causes

``` java
java.lang.IllegalStateException: Duplicate key Accept, Authorization, Cookie, X-GitHub-OTP
    at java.util.stream.Collectors.lambda$throwingMerger$115(Collectors.java:133) ~[na:1.8.0_66]
    at java.util.HashMap.merge(HashMap.java:1245) ~[na:1.8.0_66]
    at java.util.stream.Collectors.lambda$toMap$173(Collectors.java:1320) ~[na:1.8.0_66]
    at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[na:1.8.0_66]
    at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:1.8.0_66]
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_66]
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_66]
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_66]
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_66]
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_66]
    at tech.sirwellington.alchemy.http.HttpVerbImpl.extractHeadersFrom(HttpVerbImpl.java:187) ~[alchemy-http-1.1.1.jar:na]
    at tech.sirwellington.alchemy.http.HttpVerbImpl.execute(HttpVerbImpl.java:128) ~[alchemy-http-1.1.1.jar:na]
    at tech.sirwellington.alchemy.http.AlchemyMachineImpl.executeSync(AlchemyMachineImpl.java:141) ~[alchemy-http-1.1.1.jar:na]
    at tech.sirwellington.alchemy.http.AlchemyHttpStateMachine.executeSync(AlchemyHttpStateMachine.java:71) [alchemy-http-1.1.1.jar:na]
    at tech.sirwellington.alchemy.http.Step3Impl.at(Step3Impl.java:124) [alchemy-http-1.1.1.jar:na]
    at tech.sirwellington.alchemy.http.AlchemyRequest$Step3.at(AlchemyRequest.java:168) [alchemy-http-1.1.1.jar:na]
    at tech.aroma.banana.example.Main.callGithub(Main.java:101) [classes/:na]
    at tech.aroma.banana.example.Main.main(Main.java:65) [classes/:na]
Exception in thread "main" tech.sirwellington.alchemy.http.exceptions.AlchemyHttpException: java.lang.IllegalStateException: Duplicate key Accept, Authorization, Cookie, X-GitHub-OTP
    at tech.sirwellington.alchemy.http.AlchemyMachineImpl.executeSync(AlchemyMachineImpl.java:151)
    at tech.sirwellington.alchemy.http.AlchemyHttpStateMachine.executeSync(AlchemyHttpStateMachine.java:71)
    at tech.sirwellington.alchemy.http.Step3Impl.at(Step3Impl.java:124)
    at tech.sirwellington.alchemy.http.AlchemyRequest$Step3.at(AlchemyRequest.java:168)
    at tech.aroma.banana.example.Main.callGithub(Main.java:101)
    at tech.aroma.banana.example.Main.main(Main.java:65)
Caused by: java.lang.IllegalStateException: Duplicate key Accept, Authorization, Cookie, X-GitHub-OTP
    at java.util.stream.Collectors.lambda$throwingMerger$115(Collectors.java:133)
    at java.util.HashMap.merge(HashMap.java:1245)
    at java.util.stream.Collectors.lambda$toMap$173(Collectors.java:1320)
    at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
    at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at tech.sirwellington.alchemy.http.HttpVerbImpl.extractHeadersFrom(HttpVerbImpl.java:187)
    at tech.sirwellington.alchemy.http.HttpVerbImpl.execute(HttpVerbImpl.java:128)
    at tech.sirwellington.alchemy.http.AlchemyMachineImpl.executeSync(AlchemyMachineImpl.java:141)

```

**Comment by SirWellington** [comment]
The approach that I will take will make it so that multiple header values are joined with a `,`
for example

```
Accept, Authorization, Cookie, X-GitHub-OTP
```
